# Generated by Django 3.1.12 on 2025-02-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatelistings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='realestatelistings',
            index=models.Index(fields=['id'], name='real_estate_id_410a68_idx'),
        ),
        migrations.AddIndex(
            model_name='realestatelistings',
            index=models.Index(fields=['location'], name='real_estate_locatio_f9707f_idx'),
        ),
    ]
