# Generated by Django 3.1.12 on 2025-02-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250216_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'counters',
            },
        ),
        migrations.RemoveIndex(
            model_name='realestatelistings',
            name='real_estate_id_410a68_idx',
        ),
        migrations.RemoveIndex(
            model_name='realestatelistings',
            name='real_estate_locatio_f9707f_idx',
        ),
    ]
